overview_questions = ["Owner", "Gender", "Business Type", "Category of Business"]
business_recovery_questions = [
    "Confidence in business recovery",
    "Business Status During Lockdown",
    "Average no. of full-time employees before lockdown",
    "Average no. of part-time employees before lockdown",
    "Business performance compared expectation in a no-lockdown scenario",
    "If your business is running, Percentage of sales/revenue are you getting as compared with no-lockdown period",
    "Impact on profits",
    "Expected time of business recovery",
    "Intention to apply for relief",
]
credit_questions = [
    "How much cash reserves do you have?",
    "Did you try borrowing to cover expenses?",
    "Were you able to secure a loan?",
    "Where did you get the loan from? (multiple choice)",
    "Did you postpone any loan repayment due to cash crunch?",
    "Did you dip into your savings",
    "Average amount of cash dipped into from savings (in Rs)",
    "Payment to suppliers this month",
    "Payment to suppliers next month",
    "Are you getting paid by your customers?",
]
household_challenges_questions = [
    "Are you the sole earner for the household?",
    "Percent share of the business in the household when there are other sources of income",
    "Challenges in the household during lockdown (multiple choice)",
    "What takes up most of your time during the day during the lockdown period? (multiple choice)",
    "Use of digital payments",
    "How long have you been using these digital payments for your business?",
    "Overall, how do you think your usage of digital payments has changed during the lockdown?",
]
employment_questions = [
    "Were employees laid off?",
    "Average no. of workers laid off temporary",
    "Average no. of workers laid off permanently",
]


questions = [
    "Owner",
    "Gender",
    "Business Type",
    "Category of Business",
    "Business Registration",
    "Business Status During Lockdown",
    "Average no. of full-time employees before lockdown",
    "Average no. of part-time employees before lockdown",
    "Business performance compared expectation in a no-lockdown scenario",
    "If your business is running, Percentage of sales/revenue are you getting as compared with no-lockdown period",
    "Impact on profits",
    "How much cash reserves do you have?",
    "Did you try borrowing to cover expenses?",
    "Were you able to secure a loan?",
    "Where did you get the loan from? (multiple choice)",
    "Did you dip into your savings",
    "Average amount of cash dipped into from savings (in Rs)",
    "Payment to suppliers this month",
    "Payment to suppliers next month",
    "Are you getting paid by your customers?",
    "Were employees laid off?",
    "Average no. of workers laid off temporary",
    "Average no. of workers laid off permanently",
    "Did you postpone any loan repayment due to cash crunch?",
    "Confidence in business recovery",
    "Expected time of business recovery",
    "Intention to apply for relief",
    "Are you the sole earner for the household?",
    "Percent share of the business in the household when there are other sources of income",
    "Challenges in the household during lockdown (multiple choice)",
    "What takes up most of your time during the day during the lockdown period? (multiple choice)",
    "Use of digital payments",
    "How long have you been using these digital payments for your business?",
    "Overall, how do you think your usage of digital payments has changed during the lockdown?",
]
